name: VTeenWebView

options:
  xcodeVersion: "14.0"
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.quyenhan13.vteenwebviewtest
    PRODUCT_NAME: VTeenWebView
    CURRENT_PROJECT_VERSION: 999
    MARKETING_VERSION: 9.9.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    ENABLE_BITCODE: NO
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: VTeenWebView/Info.plist

targets:
  VTeenWebView:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: VTeenWebView
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.quyenhan13.vteenwebviewtest
        PRODUCT_NAME: VTeenWebView
        INFOPLIST_FILE: VTeenWebView/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CURRENT_PROJECT_VERSION: 999
        MARKETING_VERSION: 9.9.9
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        ENABLE_BITCODE: NO
